"""DOM QA with a memory Storage adapter.
Browser policy blocks navigation, including localhost. Page.set_content is used;
rehydration checks do not certify real-origin localStorage or production HTTPS.
"""
from pathlib import Path
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
from functools import partial
import threading,json,time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'carreracerdanyola.html').read_text()
def inject(page,store=None):
 payload=json.dumps(store or {},ensure_ascii=False).replace('<','\\u003c')
 script='<script>window.__store='+payload+';Object.defineProperty(window,"localStorage",{configurable:true,value:{getItem:k=>window.__store[k]??null,setItem:(k,v)=>{window.__store[k]=String(v)},removeItem:k=>{delete window.__store[k]}}});</script>'
 page.set_content(HTML.replace('<head>','<head>'+script,1))
def restore(page):
 store=page.evaluate('window.__store')
 inject(page,store)
checks=[]
def check(name,condition):
 assert condition,name
 checks.append(name)
 print('PASS',name)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1440,'height':1000})
 page=context.new_page();errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 inject(page);page.wait_for_function('window.CerdanyolaApp !== undefined')
 check('Initial Nitro category',page.evaluate('CerdanyolaApp.getCategory()')=='NITRO')
 check('26 base Nitro drivers',page.evaluate('CerdanyolaApp.getState().pilots.length')==26)
 check('No page errors on load',not errors)
 check('No hidden network calls',not requests)
 check('Noindex present','noindex' in page.locator('meta[name=robots]').get_attribute('content'))
 check('Roster explicitly hypothetical','no inscritos confirmados' in page.locator('.roster-notice').inner_text())
 check('Initial winner candidates 11',page.evaluate('CerdanyolaApp.getCalculation().podium[0].candidates.length')==11)
 page.locator('[data-rank="cristian"]').first.select_option('1')
 check('Single first place determines Nitro champion',page.evaluate('CerdanyolaApp.getCalculation().podium[0].certain[0].pilot.id')=='cristian')
 check('Occupied position disabled for another driver',page.locator('[data-rank="marc"]').first.locator('option[value="1"]').is_disabled())
 page.locator('[data-rank="marc"]').first.select_option('2')
 page.locator('[data-rank="raul-daras"]').first.select_option('3')
 page.locator('[data-rank="fabio"]').first.select_option('4')
 check('Partial top4 certain from four selectors',page.evaluate('CerdanyolaApp.getNarration().topFourCertain') is True)
 check('Still 22 missing, no forced filler positions',page.evaluate('CerdanyolaApp.getCalculation().missing.length')==22)
 check('Narration names correct runners-up','Raúl Darás, subcampeón' in page.locator('#broadcastText').inner_text())
 page.locator('[data-step="marc"][data-delta="-1"]').click()
 check('Overtake swaps two positions',page.evaluate('CerdanyolaApp.getState().pilots.find(x=>x.id==="cristian").position')=='2')
 page.locator('#undoButton').click()
 check('Undo restores positions',page.evaluate('CerdanyolaApp.getState().pilots.find(x=>x.id==="cristian").position')=='1')
 page.wait_for_timeout(250)
 page.screenshot(path=str(ROOT/'qa/nitro-desktop.png'),full_page=True)
 page.locator('#tabECO').click()
 check('Switch to ECO',page.evaluate('CerdanyolaApp.getCategory()')=='ECO')
 check('ECO has 14 separate drivers',page.evaluate('CerdanyolaApp.getState().pilots.length')==14)
 check('ECO never inherits Nitro positions',page.evaluate('CerdanyolaApp.getCalculation().assigned')==0)
 check('ECO specific warning about aggregated finals','general agregada' in page.locator('#eventPositionNote').inner_text())
 for pilot,pos in [('carles',1),('cristian',2),('joao',3),('francisco-franco',4)]:page.locator('[data-rank="'+pilot+'"]').first.select_option(str(pos))
 check('Four ECO selectors determine top4',page.evaluate('CerdanyolaApp.getNarration().topFourCertain') is True)
 check('ECO projected winner Carles',page.evaluate('CerdanyolaApp.getCalculation().podium[0].certain[0].pilot.id')=='carles')
 check('ECO projected fourth Franco',page.evaluate('CerdanyolaApp.getCalculation().podium[3].certain[0].pilot.id')=='francisco-franco')
 page.locator('#showDetails').check()
 check('Breakdown has C1 C2 C3 only',page.locator('#resultHead').inner_text().count('C3')==1 and 'Extra' not in page.locator('#resultHead').inner_text())
 page.locator('[data-detail="carles"]').click()
 check('Scoring modal displays no bonus and 3 rounds','1280' in page.locator('#detailBody').inner_text().replace('.','') and page.locator('#detailBody tbody tr').count()==3)
 page.locator('[data-close="detailDialog"]').click()
 page.locator('.title-paths summary').click()
 page.locator('#scenarioPilot').select_option('cristian')
 check('Cristian title path single row',page.locator('#scenarioRows tr').count()==1)
 check('Cristian title path Joao third or worse','Joao Barahona' in page.locator('#scenarioRows').inner_text() and '3.º o peor' in page.locator('#scenarioRows').inner_text())
 page.locator('.title-paths summary').click()
 page.locator('#showDetails').uncheck()
 page.wait_for_timeout(300);restore(page);page.wait_for_function('window.CerdanyolaApp !== undefined')
 check('Storage rehydration restores current category',page.evaluate('CerdanyolaApp.getCategory()')=='ECO')
 check('Storage rehydration restores positions',page.evaluate('CerdanyolaApp.getState().pilots.find(p=>p.id==="carles").position')=='1')
 page.locator('#tabNITRO').click()
 check('Nitro still holds its four places',page.evaluate('CerdanyolaApp.getCalculation().assigned')==4)
 page.locator('#tabECO').click()
 page.locator('#rosterButton').click();page.locator('[data-roster="diego"]').uncheck();page.locator('#rosterForm button[type=submit]').click()
 check('Roster can remove a historical driver',page.evaluate('CerdanyolaApp.getState().pilots.find(p=>p.id==="diego").active') is False)
 check('Inactive driver retains original point',page.evaluate('CerdanyolaApp.getCalculation().rows.find(r=>r.pilot.id==="diego").min')==1)
 check('Initial guide disabled after roster change',len(page.locator('#guideCards').inner_text())==0)
 page.locator('#addPilot').click();page.locator('#newName').fill('Piloto Nuevo');page.locator('#addForm button[type=submit]').click()
 check('New driver added',page.evaluate('CerdanyolaApp.getState().pilots.length')==15)
 new=page.evaluate('CerdanyolaApp.getState().pilots.at(-1)')
 check('New driver has exactly two empty historical rounds',new['history']==[None,None])
 page.locator('[data-rank="'+new['id']+'"]').first.select_option('5')
 check('New driver has own physical position',page.evaluate('CerdanyolaApp.getCalculation().rows.find(r=>r.pilot.custom).exact.todayPoints')==538)
 page.locator('#finishSection summary').click()
 check('Incomplete full closure disabled',page.locator('#finishButton').is_disabled())
 page.locator('#finishSection summary').click()
 page.wait_for_timeout(250)
 saved=page.evaluate('CerdanyolaApp.getAllStates()')
 wrong={**saved,'eventId':'lleida-2026'}
 page.locator('#importFile').set_input_files({'name':'wrong.json','mimeType':'application/json','buffer':json.dumps(wrong).encode()})
 check('Rejects Lleida backup without data changes','No se ha importado' in page.locator('#toast').inner_text())
 check('Both categories remain after bad import',page.evaluate('CerdanyolaApp.getState().pilots.length')==15)
 page.evaluate('localStorage.setItem("regionatlas:lleida-2026:race-desk:v2","sentinel")')
 page.wait_for_timeout(300);restore(page);page.wait_for_function('window.CerdanyolaApp !== undefined')
 check('Different storage key never overwrites Lleida',page.evaluate('localStorage.getItem("regionatlas:lleida-2026:race-desk:v2")')=='sentinel')
 check('Custom driver survives Storage rehydration',page.evaluate('CerdanyolaApp.getState().pilots.at(-1).name')=='Piloto Nuevo')
 page.locator('#undoButton').is_disabled()
 # Restore pristine examples for screenshots and full-close workflow through normal inputs.
 page.on('dialog',lambda d:d.accept())
 page.locator('#resetButton').click();page.locator('[data-filter="all"]').click()
 for pilot,pos in [('carles',1),('cristian',2),('joao',3),('francisco-franco',4)]:page.locator('[data-rank="'+pilot+'"]').first.select_option(str(pos))
 page.screenshot(path=str(ROOT/'qa/eco-desktop.png'),full_page=True)
 data=page.evaluate('CerdanyolaApp.getState().pilots');used={int(p['position']) for p in data if p['position']};free=iter(n for n in range(1,len(data)+1) if n not in used)
 for pilot in data:
  if not pilot['position']:page.locator('[data-rank="'+pilot['id']+'"]').first.select_option(str(next(free)))
 check('Complete all results makes final eligible',page.evaluate('CerdanyolaApp.getCalculation().finalReady') is True)
 page.locator('#finishSection summary').click();page.locator('#reviewed').check();page.locator('#finishButton').click()
 check('Final closure records final mode',page.evaluate('CerdanyolaApp.getState().mode')=='final')
 page.wait_for_timeout(300);restore(page);page.wait_for_function('window.CerdanyolaApp !== undefined')
 check('Final closure restored from Storage adapter',page.evaluate('CerdanyolaApp.getState().mode')=='final')
 page.locator('#tabNITRO').click()
 check('Closing ECO does not close Nitro',page.evaluate('CerdanyolaApp.getState().mode')=='live')
 for width in [390,360]:
  page.set_viewport_size({'width':width,'height':844})
  for cat in ['NITRO','ECO']:
   page.locator('#tab'+cat).click();page.evaluate('window.scrollTo(0,0)');page.wait_for_timeout(80)
   check(f'{cat} {width}px no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
   check(f'{cat} {width}px tabs visible',page.locator('#tab'+cat).is_visible())
   page.screenshot(path=str(ROOT/f'qa/{cat.lower()}-mobile-{width}.png'),full_page=True)
 check('No runtime errors in entire workflow',not errors)
 check('No external network requests in entire workflow',not requests)
 context.close();browser.close()

(ROOT/'qa/ui-results.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'pageErrors':errors},ensure_ascii=False,indent=2))
print('TOTAL UI CHECKS:',len(checks))
