export const AFFILIATE_BLOCKED_KEYWORDS = [
  "manual only",
  "box only",
  "empty box",
  "case only",
  "cover only",
  "replacement case",
  "repro",
  "reproduction",
  "fake",
  "poster",
  "guide",
  "strategy guide",
  "soundtrack",
  "ost",
  "digital code",
  "dlc",
  "account",
  "steam key",
  "broken",
  "not working",
  "for parts",
  "solo manual",
  "solo caja",
  "caja vacía",
  "caja vacia",
  "carátula",
  "caratula",
  "guía",
  "guia",
  "reproducción",
  "reproduccion",
  "código digital",
  "codigo digital",
  "cuenta",
  "no funciona",
  "averiado",
  "para piezas",
];
