export const AFFILIATE_BLOCKED_KEYWORDS = [
  "manual only",
  "box only",
  "empty box",
  "case only",
  "cover only",
  "cover art only",
  "artwork only",
  "artwork insert",
  "custom artwork",
  "custom cover",
  "custom case",
  "insert only",
  "inlay only",
  "back insert",
  "replacement case",
  "repro",
  "reproduction",
  "fake",
  "poster",
  "guide",
  "strategy guide",
  "soundtrack",
  "ost",
  "digital code",
  "dlc",
  "account",
  "steam key",
  "broken",
  "not working",
  "for parts",
  "solo manual",
  "solo inserto",
  "inserto trasero",
  "incrustación trasera",
  "incrustacion trasera",
  "incrustación de ilustraciones",
  "incrustacion de ilustraciones",
  "ilustraciones personalizadas",
  "solo caja",
  "caja vacía",
  "caja vacia",
  "carátula",
  "caratula",
  "guía",
  "guia",
  "reproducción",
  "reproduccion",
  "código digital",
  "codigo digital",
  "cuenta",
  "no funciona",
  "averiado",
  "para piezas",
];
