import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUTPUT_PATH = fileURLToPath(new URL("../data/catalog-edition-guides-ac-unity-valhalla.json", import.meta.url));
const REVIEWED_AT = "2026-09-15";

const evidence = (id, type, label, url, summary, supports) => ({
  id,
  type,
  label,
  ...(url ? { url } : {}),
  summary,
  supports,
});

const physicalEdition = ({
  id,
  label,
  broadRegion,
  editionType,
  marketRegions = [],
  packagingLanguages = [],
  componentLanguageEvidence = [],
  ratingSystems = [],
  barcode,
  catalogNumber,
  serial,
  releaseDate,
  physicalContents = [],
  digitalContents = [],
  catalogIds = [],
  scanSetIds = [],
  evidenceIds = [],
  variants = [],
  notes = [],
}) => ({
  id,
  label,
  broadRegion,
  editionType,
  marketRegions,
  packagingLanguages,
  componentLanguageEvidence,
  ratingSystems,
  ...(barcode ? { barcode } : {}),
  ...(catalogNumber ? { catalogNumber } : {}),
  ...(serial ? { serial } : {}),
  ...(releaseDate ? { releaseDate } : {}),
  physicalContents,
  digitalContents,
  catalogIds,
  scanSetIds,
  evidenceIds,
  variants,
  notes,
});

const unityEuropeSoftware = "Idiomas de software documentados para CUSA-00605: audio DE/ES/FR/EN/IT; pantalla DE/ZH-Hant/KO/ES/FR/EN/IT/NL/PL. No se usan como idiomas de caja.";

const unityGuide = {
  schemaVersion: 2,
  id: "assassins-creed-unity-ps4-worldwide",
  title: "Ediciones físicas mundiales de Assassin's Creed Unity en PlayStation 4",
  reviewedAt: REVIEWED_AT,
  note: "Auditoría aditiva basada exclusivamente en el dossier mundial entregado. Se conserva un único juego canónico y se separan edición conceptual, variante física, mercado, packaging e identificadores.",
  game: {
    title: "Assassin's Creed Unity",
    platformSlug: "ps4",
    canonicalCatalogId: "ps4-assassins-creed-unity",
  },
  physicalEditions: [
    physicalEdition({
      id: "ac-unity-ps4-standard-es",
      label: "Standard Edition · España",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["ES"],
      packagingLanguages: ["ES"],
      componentLanguageEvidence: [{
        component: "BOX",
        languages: ["ES"],
        basis: "OBSERVED",
        exhaustive: true,
        note: "Portada, contraportada y lomo del mismo ejemplar precintado.",
        evidenceIds: ["unity-owned-scan-es"],
      }],
      ratingSystems: ["PEGI"],
      barcode: "3307215785942",
      serial: "CUSA-00605",
      catalogIds: ["ps4-assassins-creed-unity"],
      scanSetIds: ["ps4-assassins-creed-unity"],
      evidenceIds: ["unity-owned-scan-es", "unity-fnac-es-pt", "unity-playstation-eu-languages"],
      notes: [
        "Confianza: CONFIRMED_PHYSICAL_COPY. El scan propio confirma EAN, CUSA, PEGI 18 y caja en español.",
        "El mismo SKU español tuvo circulación comercial documentada en Portugal; no constituye packaging portugués ni crea una variante PT.",
        unityEuropeSoftware,
      ],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-fr-a",
      label: "Standard Edition · Francia A",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["FR"],
      packagingLanguages: ["FR"],
      barcode: "3307215785881",
      serial: "CUSA-00605",
      evidenceIds: ["unity-france-retail"],
      notes: ["Confianza: CONFIRMED. Revisar reverso físico para cerrar el alcance exacto del packaging.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-fr-b",
      label: "Standard Edition · Francia B / candidata a reimpresión",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["FR"],
      packagingLanguages: ["FR"],
      barcode: "3307215785966",
      evidenceIds: ["unity-france-reprint"],
      notes: ["Confianza: CONFIRMED_PACKAGING_LANGUAGE. No se fusiona con 3307215785881; revisión/canal/disco exactos pendientes.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-de",
      label: "Standard Edition · Alemania",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["DE"],
      packagingLanguages: ["DE"],
      ratingSystems: ["USK"],
      barcode: "3307215785911",
      serial: "CUSA-00605",
      evidenceIds: ["unity-germany-retail"],
      notes: ["Confianza: CONFIRMED. USK 16.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-it",
      label: "Standard Edition · Italia",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["IT"],
      packagingLanguages: ["IT"],
      barcode: "3307215785935",
      serial: "CUSA-00605",
      evidenceIds: ["unity-italy-retail"],
      notes: ["Confianza: CONFIRMED_PHYSICAL_PACKAGING.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-nordic",
      label: "Standard Edition · Nordic packaging",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215785904",
      serial: "CUSA-00605",
      evidenceIds: ["unity-nordic-cover"],
      notes: ["Confianza: CONFIRMED_NORDIC_COVER. Idiomas nórdicos exactos pendientes; no se fuerza SE/DK/NO/FI ni se clasifica como Polonia.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-benelux-candidate",
      label: "Standard Edition · Benelux / internacional candidata",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215785874",
      evidenceIds: ["unity-benelux-candidate"],
      notes: ["Confianza: HIGH. Circulación documentada en NL/BE e importaciones UE; packaging pendiente, sin forzar NL-only, EN-only o FR/NL.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-eu-en-fr",
      label: "Standard Edition · Europa genérica EN/FR",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215803400",
      serial: "CUSA-00605",
      evidenceIds: ["unity-eu-generic"],
      notes: ["Confianza: CONFIRMED_EU_SKU. EN/FR son idiomas de software documentados; el idioma físico de caja continúa pendiente."],
    }),
    ...["3307215785928", "3307215803448", "3307215803462", "3307215810989"].map((barcode) => physicalEdition({
      id: `ac-unity-ps4-standard-eu-pending-${barcode}`,
      label: `Standard Edition · Europa · mapeo pendiente ${barcode}`,
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode,
      evidenceIds: ["unity-eu-pending"],
      notes: ["Estado: PENDING_MAPPING. País, packaging y revisión exacta no se publican sin evidencia adicional."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-standard-au",
      label: "Standard Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "STANDARD",
      marketRegions: ["AU"],
      ratingSystems: ["ACB MA15+"],
      serial: "CUSA-00605",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_RELEASE. Barcode pendiente; no se presume una caja compartida con Nueva Zelanda."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-na",
      label: "Standard Edition · Norteamérica",
      broadRegion: "NORTH_AMERICA",
      editionType: "STANDARD",
      marketRegions: ["US", "CA"],
      packagingLanguages: ["EN"],
      ratingSystems: ["ESRB"],
      barcode: "887256301262",
      serial: "CUSA-00663",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity"],
      evidenceIds: ["unity-na-standard"],
      notes: ["Confianza: CONFIRMED. ESRB M. Circulación del mismo SKU también documentada en México.", "UPC histórico 887256300333 permanece como LEGACY_RECORD_PENDING_MAPPING y no sustituye al Standard."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-jp",
      label: "Standard Edition · Japón",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244003506",
      serial: "PLJM-84013",
      evidenceIds: ["unity-japan-retail"],
      notes: ["Confianza: CONFIRMED. CERO Z; la familia digital CUSA-00476 se mantiene separada del código físico PLJM."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-kr",
      label: "Standard Edition · Corea",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      marketRegions: ["KR"],
      ratingSystems: ["GRAC 18"],
      serial: "PLKS-97003",
      evidenceIds: ["unity-korea-serial"],
      notes: ["Confianza: CONFIRMED_PRODUCT_CODE. Barcode, reverso e idiomas físicos pendientes; no se mezcla con Asia English/Chinese."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-asia-en-zh",
      label: "Standard Edition · Asia English/Chinese",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      packagingLanguages: ["ZH-HANT"],
      evidenceIds: ["unity-asia-language"],
      notes: ["Confianza: CONFIRMED_EXISTENCE_AND_LANGUAGE. Manual en chino tradicional; caja, barcode y product code pendientes.", "Software documentado: EN y ZH-Hant. No se asigna PLKS-97003."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-special-es",
      label: "Special Edition · España",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      marketRegions: ["ES"],
      barcode: "3307215803530",
      physicalContents: ["Juego físico"],
      digitalContents: ["Misión adicional Revolución Química"],
      catalogIds: ["ps4-assassin%27s-creed-unity-special-edition"],
      evidenceIds: ["unity-special-es"],
      notes: ["Confianza: CONFIRMED. Se mantiene separada de la Standard española."],
    }),
    ...[
      ["eu", "EU genérica", "3307215786178", []],
      ["intl-en-a", "Internacional English A", "3307215803523", ["EN"]],
      ["intl-en-b", "Internacional English B", "3307215803431", ["EN"]],
      ["intl-en-c", "Internacional English C", "3307215803561", ["EN"]],
    ].map(([suffix, label, barcode, packagingLanguages]) => physicalEdition({
      id: `ac-unity-ps4-special-${suffix}`,
      label: `Special Edition · ${label}`,
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      packagingLanguages,
      barcode,
      evidenceIds: ["unity-gamefaqs-release-data", "unity-eu-pending"],
      notes: ["Mercado/revisión interna pendiente; el barcode no se fusiona con otros Special."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-special-au",
      label: "Special Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "SPECIAL",
      marketRegions: ["AU"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Existencia física confirmada; barcode pendiente."],
    }),
    ...[
      ["es", "España", "3307215813164", "EUROPE", ["ES"], undefined],
      ["eu-a", "Europa A", "3307215792193", "EUROPE", [], undefined],
      ["eu-b", "Europa B", "3307215792117", "EUROPE", [], undefined],
      ["de", "Alemania", "3307215792155", "EUROPE", ["DE"], "CUSA-00605"],
      ["au", "Australia", "3307215792148", "OCEANIA", ["AU"], undefined],
    ].map(([suffix, label, barcode, broadRegion, marketRegions, serial]) => physicalEdition({
      id: `ac-unity-ps4-bastille-${suffix}`,
      label: `Bastille Edition · ${label}`,
      broadRegion,
      editionType: "SPECIAL",
      marketRegions,
      barcode,
      serial,
      physicalContents: suffix === "es" ? ["Juego", "Caja metálica", "Artbook", "Banda sonora", "2 litografías"] : [],
      digitalContents: suffix === "es" ? ["2 misiones para un jugador"] : [],
      evidenceIds: suffix === "es" ? ["unity-bastille-es"] : ["unity-gamefaqs-release-data", "unity-bastille-au"],
      notes: ["Variante regional de una única familia Bastille; no es una edición conceptual nueva por barcode."],
    })),
    ...[
      ["eu-a", "Europa A", "3307215791967", "EUROPE", []],
      ["eu-b", "Europa B", "3307215791912", "EUROPE", []],
      ["au", "Australia", undefined, "OCEANIA", ["AU"]],
    ].map(([suffix, label, barcode, broadRegion, marketRegions]) => physicalEdition({
      id: `ac-unity-ps4-notre-dame-${suffix}`,
      label: `Notre Dame Edition · ${label}`,
      broadRegion,
      editionType: "COLLECTOR",
      marketRegions,
      barcode,
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: [barcode ? "Mercado exacto dentro de Europa pendiente; no se fusiona con el otro EAN." : "Existencia física confirmada; barcode pendiente."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-guillotine-eu",
      label: "Guillotine Edition · Europa",
      broadRegion: "EUROPE",
      editionType: "COLLECTOR",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_EXISTENCE. Barcode pendiente; no se inventa."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-amazon-exclusive-eu",
      label: "Amazon Exclusive · Europa",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_EXISTENCE. Barcode pendiente; no se mezcla con Special Edition."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-limited-us",
      label: "Limited Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "LIMITED",
      marketRegions: ["US"],
      barcode: "887256300302",
      serial: "CUSA-00663",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-limited-edition"],
      evidenceIds: ["unity-limited-na"],
      notes: ["Confianza: CONFIRMED. No se fusiona con Limited Canadá/México."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-limited-ca-mx",
      label: "Limited Edition · Canadá / México",
      broadRegion: "NORTH_AMERICA",
      editionType: "LIMITED",
      marketRegions: ["CA", "MX"],
      barcode: "887256300340",
      serial: "CUSA-00663LEL",
      catalogNumber: "UBP30500952-CVRT",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Identificadores CUSA-00663LEL y UBP30500952-CVRT preservados por separado."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-walmart-us",
      label: "Walmart Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "SPECIAL",
      marketRegions: ["US"],
      barcode: "887256301286",
      serial: "CUSA-00663LEW",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-walmart-edition"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-collector-us",
      label: "Collector's Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "COLLECTOR",
      marketRegions: ["US"],
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-collector%27s-edition"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      variants: [
        { id: "ac-unity-collector-us-upc-887256301309", label: "US Collector A", barcode: "887256301309", priceIdentity: "ac-unity-ps4-collector-us-887256301309", notes: ["Mapeo final de caja/plataforma pendiente."], evidenceIds: ["unity-gamefaqs-release-data"] },
        { id: "ac-unity-collector-us-upc-887256301323", label: "US Collector B", barcode: "887256301323", priceIdentity: "ac-unity-ps4-collector-us-887256301323", notes: ["Necesita verificación física antes de afirmarlo como PS4."], evidenceIds: ["unity-gamefaqs-release-data"] },
      ],
      notes: ["Los dos UPC históricos permanecen separados y pendientes de mapeo; la ficha pública y su precio no se alteran."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-ubi-the-best-jp",
      label: "Ubi the Best · Japón",
      broadRegion: "ASIA",
      editionType: "BUDGET_REISSUE",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244003919",
      serial: "PLJM-84051",
      releaseDate: "2016-03-03",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Reedición separada de PLJM-84013."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-playstation-hits-us",
      label: "PlayStation Hits · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "BUDGET_REISSUE",
      marketRegions: ["US"],
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-playstation-hits"],
      notes: ["Ficha pública, URL y portada existentes preservadas. El dossier entregado no aporta barcode/product code para esta reedición."],
    }),
  ],
  evidence: [
    evidence("unity-owned-scan-es", "REAL_SCAN", "Escaneos propios de la Standard PAL España", undefined, "Portada, contraportada y lomo del ejemplar precintado confirman caja española, EAN 3307215785942, CUSA-00605 y PEGI 18.", ["Standard España", "EAN", "CUSA", "packaging español", "PEGI"]),
    evidence("unity-playstation-eu-languages", "PUBLISHER_DOCUMENTATION", "PlayStation España · idiomas del software europeo", "https://www.playstation.com/es-es/games/assassins-creed-unity/", "Documenta audio DE/ES/FR/EN/IT y pantalla DE/ZH tradicional/KO/ES/FR/EN/IT/NL/PL para la familia europea.", ["softwareLanguages CUSA-00605"]),
    evidence("unity-fnac-es-pt", "RETAILER_ASSET", "Fnac España y Portugal · Standard española", "https://www.fnac.es/Assassin-s-Creed-Unity-PS4-Videojuego-PS4/a1024411", "Confirma EAN 3307215785942; Fnac Portugal comercializó el mismo SKU como español.", ["Standard España", "circulación Portugal"]),
    evidence("unity-france-retail", "RETAILER_ASSET", "Fnac/Auchan Francia · Standard A", "https://www.fnac.com/a7526550/Assassin-s-Creed-Unity-PS4-Jeu-video-PlayStation-4", "Confirma el EAN francés 3307215785881.", ["France Standard A"]),
    evidence("unity-france-reprint", "RETAILER_PHOTO_CONFIRMED", "Fnac/Consollection/listing físico · Standard B", "https://www.fnac.com/a7988786/Assassin-s-Creed-Unity-PS4-Jeu-video-PlayStation-4", "Confirma EAN 3307215785966 y packaging francés; naturaleza exacta de la revisión pendiente.", ["France Standard B"]),
    evidence("unity-germany-retail", "RETAILER_PHOTO_CONFIRMED", "Retroplace/Rebuy · Alemania", "https://www.retroplace.com/en/games/153987--assassins-creed-unity", "Confirma Alemania, CUSA-00605, EAN 3307215785911, alemán y USK 16.", ["Standard Alemania"]),
    evidence("unity-italy-retail", "RETAILER_ASSET", "DB-Line/Gamelife · Italia", "https://www.dbline.it/it/products/online-catalog/detail/PS40495", "Confirma EAN 3307215785935 y caja/manual en italiano.", ["Standard Italia"]),
    evidence("unity-nordic-cover", "REAL_PHOTO", "Proshop/listing con portada nórdica", "https://www.proshop.pl/Gry/Assassins-Creed-Unity-Sony-PlayStation-4-Akcja/2463816", "Confirma EAN 3307215785904 y clasificación de packaging nórdico sin cerrar idiomas exactos.", ["Standard Nordic"]),
    evidence("unity-benelux-candidate", "RETAILER_ASSET", "Bol Netherlands · candidato Benelux/internacional", "https://www.bol.com/", "El dossier vincula 3307215785874 a circulación NL/BE/import; identidad física exacta pendiente.", ["Benelux candidate"]),
    evidence("unity-eu-generic", "RETAILER_ASSET", "World of Games · SKU europeo genérico", "https://www.wog.ch/en/index.cfm/details/product/38115-Assassins-Creed-Unity-EN", "Confirma EAN 3307215803400 y software EN/FR, sin cerrar packaging.", ["Europe EN/FR generic"]),
    evidence("unity-eu-pending", "RETAILER_ASSET", "Rebuy · referencias de importación europea", "https://www.rebuy.de/i%2C9234628/playstation-4/assassin-s-creed-unity-eu-import", "Registra varios EAN europeos cuyos mercados y packaging siguen pendientes.", ["EU pending mappings", "Special international mappings"]),
    evidence("unity-special-es", "RETAILER_ASSET", "Fnac España · Special Edition", "https://www.fnac.es/Assassin-s-Creed-Unity-Edicion-Especial-PS4-Videojuego-PS4/a1025479", "Confirma EAN 3307215803530 y la misión Revolución Química.", ["Special Edition España"]),
    evidence("unity-bastille-es", "RETAILER_ASSET", "Fnac España · Bastille Edition", "https://www.fnac.es/Assassin-s-Creed-Unity-Edicion-Bastille-PS4-Videojuego-PS4/a1032597", "Confirma EAN 3307215813164 y contenidos de Bastille España.", ["Bastille Edition España"]),
    evidence("unity-bastille-au", "RETAILER_ASSET", "Gamesmen Australia · Bastille Edition", "https://www.gamesmen.com.au/ps4-assassins-creed-5-unity-bastille-edition", "Confirma la variante australiana y EAN 3307215792148.", ["Bastille Edition Australia"]),
    evidence("unity-gamefaqs-release-data", "UNKNOWN", "GameFAQs · datos de lanzamiento suministrados", "https://gamefaqs.gamespot.com/ps4/772633-assassins-creed-unity/data", "Fuente agregada del dossier para ediciones y códigos; los conflictos y huecos permanecen pendientes.", ["ediciones europeas", "Australia", "Norteamérica", "Japón"]),
    evidence("unity-na-standard", "RETAILER_PHOTO_CONFIRMED", "Best Buy/VGCollect · Standard Norteamérica", "https://www.bestbuy.com/product/assassins-creed-unity-standard-edition-playstation-4/J3ZY3J2G79", "Confirma UPC 887256301262, CUSA-00663, caja inglesa y ESRB M.", ["Standard Norteamérica"]),
    evidence("unity-limited-na", "RETAILER_ASSET", "Play-Asia · Limited Edition USA", "https://www.play-asia.com/en/assassins-creed-unity-limited-edition/13/70a38r", "Confirma la Limited USA separada de Standard y de Canadá/México.", ["Limited Edition USA"]),
    evidence("unity-japan-retail", "RETAILER_ASSET", "MediaWorld Japón · Standard", "https://store.shopping.yahoo.co.jp/media-world/10440044001.html", "Confirma JAN 4949244003506 y PLJM-84013.", ["Standard Japón"]),
    evidence("unity-korea-serial", "PUBLISHER_DOCUMENTATION", "SerialStation · código coreano", "https://serialstation.com/games/c8489e98-cbc1-4c11-b5ea-7fdc4e4f40f6", "Confirma PLKS-97003 sin aportar barcode ni reverso.", ["Standard Corea"]),
    evidence("unity-asia-language", "RETAILER_ASSET", "Play-Asia/YesAsia · English & Chinese", "https://www.play-asia.com/en/assassins-creed-unity-english-chinese/13/708035", "Confirma existencia asiática y software EN/ZH-Hant; YesAsia declara manual chino.", ["Standard Asia English/Chinese"]),
  ],
  sources: [
    { label: "Orden local: regionatlas_codex_ac_unity_worldwide_variants.md" },
    { label: "Escaneos propios registrados en RegionAtlas" },
  ],
  evidenceNote: "No se realizó investigación externa. Las afirmaciones proceden del documento entregado y de los escaneos propios ya registrados; todo conflicto de plataforma, país, barcode o packaging continúa marcado como pendiente.",
};

unityGuide.editionFamilies = [{
  id: "documented-worldwide-editions",
  label: "Ediciones físicas documentadas",
  representativeCatalogId: unityGuide.game.canonicalCatalogId,
  physicalEditionIds: unityGuide.physicalEditions.map((edition) => edition.id),
  priceConditions: ["sealed", "newRetail", "complete"],
}];

const document = { schemaVersion: 2, guides: [unityGuide] };
const serialized = `${JSON.stringify(document, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    // The comparison below reports the missing generated artifact.
  }
  if (current !== serialized) {
    console.error("catalog-edition-guides-ac-unity-valhalla.json is not up to date");
    process.exitCode = 1;
  } else {
    console.log("Assassin's Creed Unity V2 guide is reproducible");
  }
} else {
  writeFileSync(OUTPUT_PATH, serialized);
  console.log(`Wrote ${OUTPUT_PATH}`);
}
