import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUTPUT_PATH = fileURLToPath(new URL("../data/catalog-edition-guides-ac-unity-valhalla.json", import.meta.url));
const REVIEWED_AT = "2026-09-15";

const evidence = (id, type, label, url, summary, supports) => ({
  id,
  type,
  label,
  ...(url ? { url } : {}),
  summary,
  supports,
});

const physicalEdition = ({
  id,
  label,
  broadRegion,
  editionType,
  marketRegions = [],
  packagingLanguages = [],
  componentLanguageEvidence = [],
  ratingSystems = [],
  barcode,
  catalogNumber,
  serial,
  releaseDate,
  physicalContents = [],
  digitalContents = [],
  catalogIds = [],
  scanSetIds = [],
  evidenceIds = [],
  variants = [],
  notes = [],
}) => ({
  id,
  label,
  broadRegion,
  editionType,
  marketRegions,
  packagingLanguages,
  componentLanguageEvidence,
  ratingSystems,
  ...(barcode ? { barcode } : {}),
  ...(catalogNumber ? { catalogNumber } : {}),
  ...(serial ? { serial } : {}),
  ...(releaseDate ? { releaseDate } : {}),
  physicalContents,
  digitalContents,
  catalogIds,
  scanSetIds,
  evidenceIds,
  variants,
  notes,
});

const unityEuropeSoftware = "Idiomas de software documentados para CUSA-00605: audio DE/ES/FR/EN/IT; pantalla DE/ZH-Hant/KO/ES/FR/EN/IT/NL/PL. No se usan como idiomas de caja.";

const unityGuide = {
  schemaVersion: 2,
  id: "assassins-creed-unity-ps4-worldwide",
  title: "Ediciones físicas mundiales de Assassin's Creed Unity en PlayStation 4",
  reviewedAt: REVIEWED_AT,
  note: "Auditoría aditiva basada exclusivamente en el dossier mundial entregado. Se conserva un único juego canónico y se separan edición conceptual, variante física, mercado, packaging e identificadores.",
  game: {
    title: "Assassin's Creed Unity",
    platformSlug: "ps4",
    canonicalCatalogId: "ps4-assassins-creed-unity",
  },
  physicalEditions: [
    physicalEdition({
      id: "ac-unity-ps4-standard-es",
      label: "Standard Edition · España",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["ES"],
      packagingLanguages: ["ES"],
      componentLanguageEvidence: [{
        component: "BOX",
        languages: ["ES"],
        basis: "OBSERVED",
        exhaustive: true,
        note: "Portada, contraportada y lomo del mismo ejemplar precintado.",
        evidenceIds: ["unity-owned-scan-es"],
      }],
      ratingSystems: ["PEGI"],
      barcode: "3307215785942",
      serial: "CUSA-00605",
      catalogIds: ["ps4-assassins-creed-unity"],
      scanSetIds: ["ps4-assassins-creed-unity"],
      evidenceIds: ["unity-owned-scan-es", "unity-fnac-es-pt", "unity-playstation-eu-languages"],
      notes: [
        "Confianza: CONFIRMED_PHYSICAL_COPY. El scan propio confirma EAN, CUSA, PEGI 18 y caja en español.",
        "El mismo SKU español tuvo circulación comercial documentada en Portugal; no constituye packaging portugués ni crea una variante PT.",
        unityEuropeSoftware,
      ],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-fr-a",
      label: "Standard Edition · Francia A",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["FR"],
      packagingLanguages: ["FR"],
      barcode: "3307215785881",
      serial: "CUSA-00605",
      evidenceIds: ["unity-france-retail"],
      notes: ["Confianza: CONFIRMED. Revisar reverso físico para cerrar el alcance exacto del packaging.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-fr-b",
      label: "Standard Edition · Francia B / candidata a reimpresión",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["FR"],
      packagingLanguages: ["FR"],
      barcode: "3307215785966",
      evidenceIds: ["unity-france-reprint"],
      notes: ["Confianza: CONFIRMED_PACKAGING_LANGUAGE. No se fusiona con 3307215785881; revisión/canal/disco exactos pendientes.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-de",
      label: "Standard Edition · Alemania",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["DE"],
      packagingLanguages: ["DE"],
      ratingSystems: ["USK"],
      barcode: "3307215785911",
      serial: "CUSA-00605",
      evidenceIds: ["unity-germany-retail"],
      notes: ["Confianza: CONFIRMED. USK 16.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-it",
      label: "Standard Edition · Italia",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["IT"],
      packagingLanguages: ["IT"],
      barcode: "3307215785935",
      serial: "CUSA-00605",
      evidenceIds: ["unity-italy-retail"],
      notes: ["Confianza: CONFIRMED_PHYSICAL_PACKAGING.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-nordic",
      label: "Standard Edition · Nordic packaging",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215785904",
      serial: "CUSA-00605",
      evidenceIds: ["unity-nordic-cover"],
      notes: ["Confianza: CONFIRMED_NORDIC_COVER. Idiomas nórdicos exactos pendientes; no se fuerza SE/DK/NO/FI ni se clasifica como Polonia.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-benelux-candidate",
      label: "Standard Edition · Benelux / internacional candidata",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215785874",
      evidenceIds: ["unity-benelux-candidate"],
      notes: ["Confianza: HIGH. Circulación documentada en NL/BE e importaciones UE; packaging pendiente, sin forzar NL-only, EN-only o FR/NL.", unityEuropeSoftware],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-eu-en-fr",
      label: "Standard Edition · Europa genérica EN/FR",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307215803400",
      serial: "CUSA-00605",
      evidenceIds: ["unity-eu-generic"],
      notes: ["Confianza: CONFIRMED_EU_SKU. EN/FR son idiomas de software documentados; el idioma físico de caja continúa pendiente."],
    }),
    ...["3307215785928", "3307215803448", "3307215803462", "3307215810989"].map((barcode) => physicalEdition({
      id: `ac-unity-ps4-standard-eu-pending-${barcode}`,
      label: `Standard Edition · Europa · mapeo pendiente ${barcode}`,
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode,
      evidenceIds: ["unity-eu-pending"],
      notes: ["Estado: PENDING_MAPPING. País, packaging y revisión exacta no se publican sin evidencia adicional."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-standard-au",
      label: "Standard Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "STANDARD",
      marketRegions: ["AU"],
      ratingSystems: ["ACB MA15+"],
      serial: "CUSA-00605",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_RELEASE. Barcode pendiente; no se presume una caja compartida con Nueva Zelanda."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-na",
      label: "Standard Edition · Norteamérica",
      broadRegion: "NORTH_AMERICA",
      editionType: "STANDARD",
      marketRegions: ["US", "CA"],
      packagingLanguages: ["EN"],
      ratingSystems: ["ESRB"],
      barcode: "887256301262",
      serial: "CUSA-00663",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity"],
      evidenceIds: ["unity-na-standard"],
      notes: ["Confianza: CONFIRMED. ESRB M. Circulación del mismo SKU también documentada en México.", "UPC histórico 887256300333 permanece como LEGACY_RECORD_PENDING_MAPPING y no sustituye al Standard."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-jp",
      label: "Standard Edition · Japón",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244003506",
      serial: "PLJM-84013",
      evidenceIds: ["unity-japan-retail"],
      notes: ["Confianza: CONFIRMED. CERO Z; la familia digital CUSA-00476 se mantiene separada del código físico PLJM."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-kr",
      label: "Standard Edition · Corea",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      marketRegions: ["KR"],
      ratingSystems: ["GRAC 18"],
      serial: "PLKS-97003",
      evidenceIds: ["unity-korea-serial"],
      notes: ["Confianza: CONFIRMED_PRODUCT_CODE. Barcode, reverso e idiomas físicos pendientes; no se mezcla con Asia English/Chinese."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-standard-asia-en-zh",
      label: "Standard Edition · Asia English/Chinese",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      packagingLanguages: ["ZH-HANT"],
      evidenceIds: ["unity-asia-language"],
      notes: ["Confianza: CONFIRMED_EXISTENCE_AND_LANGUAGE. Manual en chino tradicional; caja, barcode y product code pendientes.", "Software documentado: EN y ZH-Hant. No se asigna PLKS-97003."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-special-es",
      label: "Special Edition · España",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      marketRegions: ["ES"],
      barcode: "3307215803530",
      physicalContents: ["Juego físico"],
      digitalContents: ["Misión adicional Revolución Química"],
      catalogIds: ["ps4-assassin%27s-creed-unity-special-edition"],
      evidenceIds: ["unity-special-es"],
      notes: ["Confianza: CONFIRMED. Se mantiene separada de la Standard española."],
    }),
    ...[
      ["eu", "EU genérica", "3307215786178", []],
      ["intl-en-a", "Internacional English A", "3307215803523", ["EN"]],
      ["intl-en-b", "Internacional English B", "3307215803431", ["EN"]],
      ["intl-en-c", "Internacional English C", "3307215803561", ["EN"]],
    ].map(([suffix, label, barcode, packagingLanguages]) => physicalEdition({
      id: `ac-unity-ps4-special-${suffix}`,
      label: `Special Edition · ${label}`,
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      packagingLanguages,
      barcode,
      evidenceIds: ["unity-gamefaqs-release-data", "unity-eu-pending"],
      notes: ["Mercado/revisión interna pendiente; el barcode no se fusiona con otros Special."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-special-au",
      label: "Special Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "SPECIAL",
      marketRegions: ["AU"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Existencia física confirmada; barcode pendiente."],
    }),
    ...[
      ["es", "España", "3307215813164", "EUROPE", ["ES"], undefined],
      ["eu-a", "Europa A", "3307215792193", "EUROPE", [], undefined],
      ["eu-b", "Europa B", "3307215792117", "EUROPE", [], undefined],
      ["de", "Alemania", "3307215792155", "EUROPE", ["DE"], "CUSA-00605"],
      ["au", "Australia", "3307215792148", "OCEANIA", ["AU"], undefined],
    ].map(([suffix, label, barcode, broadRegion, marketRegions, serial]) => physicalEdition({
      id: `ac-unity-ps4-bastille-${suffix}`,
      label: `Bastille Edition · ${label}`,
      broadRegion,
      editionType: "SPECIAL",
      marketRegions,
      barcode,
      serial,
      physicalContents: suffix === "es" ? ["Juego", "Caja metálica", "Artbook", "Banda sonora", "2 litografías"] : [],
      digitalContents: suffix === "es" ? ["2 misiones para un jugador"] : [],
      evidenceIds: suffix === "es" ? ["unity-bastille-es"] : ["unity-gamefaqs-release-data", "unity-bastille-au"],
      notes: ["Variante regional de una única familia Bastille; no es una edición conceptual nueva por barcode."],
    })),
    ...[
      ["eu-a", "Europa A", "3307215791967", "EUROPE", []],
      ["eu-b", "Europa B", "3307215791912", "EUROPE", []],
      ["au", "Australia", undefined, "OCEANIA", ["AU"]],
    ].map(([suffix, label, barcode, broadRegion, marketRegions]) => physicalEdition({
      id: `ac-unity-ps4-notre-dame-${suffix}`,
      label: `Notre Dame Edition · ${label}`,
      broadRegion,
      editionType: "COLLECTOR",
      marketRegions,
      barcode,
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: [barcode ? "Mercado exacto dentro de Europa pendiente; no se fusiona con el otro EAN." : "Existencia física confirmada; barcode pendiente."],
    })),
    physicalEdition({
      id: "ac-unity-ps4-guillotine-eu",
      label: "Guillotine Edition · Europa",
      broadRegion: "EUROPE",
      editionType: "COLLECTOR",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_EXISTENCE. Barcode pendiente; no se inventa."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-amazon-exclusive-eu",
      label: "Amazon Exclusive · Europa",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_EXISTENCE. Barcode pendiente; no se mezcla con Special Edition."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-limited-us",
      label: "Limited Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "LIMITED",
      marketRegions: ["US"],
      barcode: "887256300302",
      serial: "CUSA-00663",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-limited-edition"],
      evidenceIds: ["unity-limited-na"],
      notes: ["Confianza: CONFIRMED. No se fusiona con Limited Canadá/México."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-limited-ca-mx",
      label: "Limited Edition · Canadá / México",
      broadRegion: "NORTH_AMERICA",
      editionType: "LIMITED",
      marketRegions: ["CA", "MX"],
      barcode: "887256300340",
      serial: "CUSA-00663LEL",
      catalogNumber: "UBP30500952-CVRT",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Identificadores CUSA-00663LEL y UBP30500952-CVRT preservados por separado."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-walmart-us",
      label: "Walmart Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "SPECIAL",
      marketRegions: ["US"],
      barcode: "887256301286",
      serial: "CUSA-00663LEW",
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-walmart-edition"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-collector-us",
      label: "Collector's Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "COLLECTOR",
      marketRegions: ["US"],
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-collector%27s-edition"],
      evidenceIds: ["unity-gamefaqs-release-data"],
      variants: [
        { id: "ac-unity-collector-us-upc-887256301309", label: "US Collector A", barcode: "887256301309", priceIdentity: "ac-unity-ps4-collector-us-887256301309", notes: ["Mapeo final de caja/plataforma pendiente."], evidenceIds: ["unity-gamefaqs-release-data"] },
        { id: "ac-unity-collector-us-upc-887256301323", label: "US Collector B", barcode: "887256301323", priceIdentity: "ac-unity-ps4-collector-us-887256301323", notes: ["Necesita verificación física antes de afirmarlo como PS4."], evidenceIds: ["unity-gamefaqs-release-data"] },
      ],
      notes: ["Los dos UPC históricos permanecen separados y pendientes de mapeo; la ficha pública y su precio no se alteran."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-ubi-the-best-jp",
      label: "Ubi the Best · Japón",
      broadRegion: "ASIA",
      editionType: "BUDGET_REISSUE",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244003919",
      serial: "PLJM-84051",
      releaseDate: "2016-03-03",
      evidenceIds: ["unity-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Reedición separada de PLJM-84013."],
    }),
    physicalEdition({
      id: "ac-unity-ps4-playstation-hits-us",
      label: "PlayStation Hits · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "BUDGET_REISSUE",
      marketRegions: ["US"],
      catalogIds: ["ps4-usa-assassin%27s-creed-unity-playstation-hits"],
      notes: ["Ficha pública, URL y portada existentes preservadas. El dossier entregado no aporta barcode/product code para esta reedición."],
    }),
  ],
  evidence: [
    evidence("unity-owned-scan-es", "REAL_SCAN", "Escaneos propios de la Standard PAL España", undefined, "Portada, contraportada y lomo del ejemplar precintado confirman caja española, EAN 3307215785942, CUSA-00605 y PEGI 18.", ["Standard España", "EAN", "CUSA", "packaging español", "PEGI"]),
    evidence("unity-playstation-eu-languages", "PUBLISHER_DOCUMENTATION", "PlayStation España · idiomas del software europeo", "https://www.playstation.com/es-es/games/assassins-creed-unity/", "Documenta audio DE/ES/FR/EN/IT y pantalla DE/ZH tradicional/KO/ES/FR/EN/IT/NL/PL para la familia europea.", ["softwareLanguages CUSA-00605"]),
    evidence("unity-fnac-es-pt", "RETAILER_ASSET", "Fnac España y Portugal · Standard española", "https://www.fnac.es/Assassin-s-Creed-Unity-PS4-Videojuego-PS4/a1024411", "Confirma EAN 3307215785942; Fnac Portugal comercializó el mismo SKU como español.", ["Standard España", "circulación Portugal"]),
    evidence("unity-france-retail", "RETAILER_ASSET", "Fnac/Auchan Francia · Standard A", "https://www.fnac.com/a7526550/Assassin-s-Creed-Unity-PS4-Jeu-video-PlayStation-4", "Confirma el EAN francés 3307215785881.", ["France Standard A"]),
    evidence("unity-france-reprint", "RETAILER_PHOTO_CONFIRMED", "Fnac/Consollection/listing físico · Standard B", "https://www.fnac.com/a7988786/Assassin-s-Creed-Unity-PS4-Jeu-video-PlayStation-4", "Confirma EAN 3307215785966 y packaging francés; naturaleza exacta de la revisión pendiente.", ["France Standard B"]),
    evidence("unity-germany-retail", "RETAILER_PHOTO_CONFIRMED", "Retroplace/Rebuy · Alemania", "https://www.retroplace.com/en/games/153987--assassins-creed-unity", "Confirma Alemania, CUSA-00605, EAN 3307215785911, alemán y USK 16.", ["Standard Alemania"]),
    evidence("unity-italy-retail", "RETAILER_ASSET", "DB-Line/Gamelife · Italia", "https://www.dbline.it/it/products/online-catalog/detail/PS40495", "Confirma EAN 3307215785935 y caja/manual en italiano.", ["Standard Italia"]),
    evidence("unity-nordic-cover", "REAL_PHOTO", "Proshop/listing con portada nórdica", "https://www.proshop.pl/Gry/Assassins-Creed-Unity-Sony-PlayStation-4-Akcja/2463816", "Confirma EAN 3307215785904 y clasificación de packaging nórdico sin cerrar idiomas exactos.", ["Standard Nordic"]),
    evidence("unity-benelux-candidate", "RETAILER_ASSET", "Bol Netherlands · candidato Benelux/internacional", "https://www.bol.com/", "El dossier vincula 3307215785874 a circulación NL/BE/import; identidad física exacta pendiente.", ["Benelux candidate"]),
    evidence("unity-eu-generic", "RETAILER_ASSET", "World of Games · SKU europeo genérico", "https://www.wog.ch/en/index.cfm/details/product/38115-Assassins-Creed-Unity-EN", "Confirma EAN 3307215803400 y software EN/FR, sin cerrar packaging.", ["Europe EN/FR generic"]),
    evidence("unity-eu-pending", "RETAILER_ASSET", "Rebuy · referencias de importación europea", "https://www.rebuy.de/i%2C9234628/playstation-4/assassin-s-creed-unity-eu-import", "Registra varios EAN europeos cuyos mercados y packaging siguen pendientes.", ["EU pending mappings", "Special international mappings"]),
    evidence("unity-special-es", "RETAILER_ASSET", "Fnac España · Special Edition", "https://www.fnac.es/Assassin-s-Creed-Unity-Edicion-Especial-PS4-Videojuego-PS4/a1025479", "Confirma EAN 3307215803530 y la misión Revolución Química.", ["Special Edition España"]),
    evidence("unity-bastille-es", "RETAILER_ASSET", "Fnac España · Bastille Edition", "https://www.fnac.es/Assassin-s-Creed-Unity-Edicion-Bastille-PS4-Videojuego-PS4/a1032597", "Confirma EAN 3307215813164 y contenidos de Bastille España.", ["Bastille Edition España"]),
    evidence("unity-bastille-au", "RETAILER_ASSET", "Gamesmen Australia · Bastille Edition", "https://www.gamesmen.com.au/ps4-assassins-creed-5-unity-bastille-edition", "Confirma la variante australiana y EAN 3307215792148.", ["Bastille Edition Australia"]),
    evidence("unity-gamefaqs-release-data", "UNKNOWN", "GameFAQs · datos de lanzamiento suministrados", "https://gamefaqs.gamespot.com/ps4/772633-assassins-creed-unity/data", "Fuente agregada del dossier para ediciones y códigos; los conflictos y huecos permanecen pendientes.", ["ediciones europeas", "Australia", "Norteamérica", "Japón"]),
    evidence("unity-na-standard", "RETAILER_PHOTO_CONFIRMED", "Best Buy/VGCollect · Standard Norteamérica", "https://www.bestbuy.com/product/assassins-creed-unity-standard-edition-playstation-4/J3ZY3J2G79", "Confirma UPC 887256301262, CUSA-00663, caja inglesa y ESRB M.", ["Standard Norteamérica"]),
    evidence("unity-limited-na", "RETAILER_ASSET", "Play-Asia · Limited Edition USA", "https://www.play-asia.com/en/assassins-creed-unity-limited-edition/13/70a38r", "Confirma la Limited USA separada de Standard y de Canadá/México.", ["Limited Edition USA"]),
    evidence("unity-japan-retail", "RETAILER_ASSET", "MediaWorld Japón · Standard", "https://store.shopping.yahoo.co.jp/media-world/10440044001.html", "Confirma JAN 4949244003506 y PLJM-84013.", ["Standard Japón"]),
    evidence("unity-korea-serial", "PUBLISHER_DOCUMENTATION", "SerialStation · código coreano", "https://serialstation.com/games/c8489e98-cbc1-4c11-b5ea-7fdc4e4f40f6", "Confirma PLKS-97003 sin aportar barcode ni reverso.", ["Standard Corea"]),
    evidence("unity-asia-language", "RETAILER_ASSET", "Play-Asia/YesAsia · English & Chinese", "https://www.play-asia.com/en/assassins-creed-unity-english-chinese/13/708035", "Confirma existencia asiática y software EN/ZH-Hant; YesAsia declara manual chino.", ["Standard Asia English/Chinese"]),
  ],
  sources: [
    { label: "Orden local: regionatlas_codex_ac_unity_worldwide_variants.md" },
    { label: "Escaneos propios registrados en RegionAtlas" },
  ],
  evidenceNote: "No se realizó investigación externa. Las afirmaciones proceden del documento entregado y de los escaneos propios ya registrados; todo conflicto de plataforma, país, barcode o packaging continúa marcado como pendiente.",
};

const valhallaGuide = {
  schemaVersion: 2,
  id: "assassins-creed-valhalla-ps4-worldwide",
  title: "Ediciones físicas mundiales de Assassin's Creed Valhalla en PlayStation 4",
  reviewedAt: REVIEWED_AT,
  note: "El juego base, sus ediciones físicas y sus variantes regionales se mantienen separados de la expansión Dawn of Ragnarök y de los productos físicos que sólo contienen un código.",
  game: {
    title: "Assassin's Creed Valhalla",
    platformSlug: "ps4",
    canonicalCatalogId: "ps4-assassins-creed-valhalla",
  },
  physicalEditions: [
    physicalEdition({
      id: "ac-valhalla-ps4-standard-es",
      label: "Standard Edition · España",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["ES"],
      packagingLanguages: ["ES"],
      componentLanguageEvidence: [{
        component: "BOX",
        languages: ["ES"],
        basis: "OBSERVED",
        exhaustive: true,
        note: "Portada, contraportada y lomo del mismo ejemplar precintado.",
        evidenceIds: ["valhalla-owned-scan-es"],
      }],
      ratingSystems: ["PEGI"],
      barcode: "3307216168379",
      serial: "CUSA-18534",
      catalogIds: ["ps4-assassins-creed-valhalla"],
      scanSetIds: ["ps4-assassins-creed-valhalla"],
      evidenceIds: ["valhalla-owned-scan-es", "valhalla-spain-retail"],
      notes: [
        "Confianza: CONFIRMED_PHYSICAL_PACKAGING. El scan propio confirma EAN, CUSA y caja en español.",
        "La contraportada indica que las voces en castellano requieren descarga; esta disponibilidad de software no se copia al packaging.",
      ],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-fr-nl",
      label: "Standard Edition · Francia / packaging FR-NL",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["FR", "BE", "NL"],
      packagingLanguages: ["FR", "NL"],
      barcode: "3307216168287",
      serial: "CUSA-18534",
      evidenceIds: ["valhalla-france-retail"],
      notes: ["Confianza: CONFIRMED_PHYSICAL_PACKAGING. La misma caja FR/NL circula en FR/BE/NL; no se duplica como Benelux."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-pl",
      label: "Standard Edition · Polonia",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["PL"],
      packagingLanguages: ["PL"],
      barcode: "3307216168348",
      evidenceIds: ["valhalla-poland-retail"],
      notes: ["Confianza: CONFIRMED_PHYSICAL_PACKAGING. Software con subtítulos polacos; no se reclasifica como Ultimate por títulos erróneos de marketplace."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-en",
      label: "Standard Edition · English packaging / UK-internacional",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["GB"],
      packagingLanguages: ["EN"],
      barcode: "3307216168362",
      evidenceIds: ["valhalla-english-pack"],
      notes: ["Confianza: CONFIRMED_PHYSICAL_PACKAGING. Ventas de importación no convierten esta caja en ES o IT."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-at",
      label: "Standard Edition · Austria / PEGI-AT",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["AT"],
      ratingSystems: ["PEGI"],
      barcode: "3307216168324",
      evidenceIds: ["valhalla-austria-retail"],
      notes: ["Confianza: CONFIRMED_MARKET. Packaging pendiente; no se convierte en Alemania/USK."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-it-market-en-cover",
      label: "Standard Edition · mercado Italia / caja inglesa",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      marketRegions: ["IT"],
      packagingLanguages: ["EN"],
      barcode: "3307216168294",
      evidenceIds: ["valhalla-italy-market"],
      notes: ["Identidad territorial: PENDING. Evidencia de software italiano, pero no de packaging italiano; DEDICATED_ITALIAN_STANDARD sigue sin confirmar."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-eu-cusa18535",
      label: "Standard Edition · Europa genérica",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      ratingSystems: ["PEGI"],
      barcode: "3307216168300",
      serial: "CUSA-18535",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED_SKU. Mercado y packaging pendientes; CUSA-18535 no se colapsa con CUSA-18534."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-eu-pending-3307216168317",
      label: "Standard Edition · Europa · mapeo pendiente 3307216168317",
      broadRegion: "EUROPE",
      editionType: "STANDARD",
      barcode: "3307216168317",
      serial: "CUSA-18534",
      evidenceIds: ["valhalla-eu-pending"],
      notes: ["Estado: PENDING_TERRITORIAL_MAPPING. No se asigna a ES/FR/DE por el país del retailer."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-au",
      label: "Standard Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "STANDARD",
      marketRegions: ["AU"],
      ratingSystems: ["ACB MA"],
      barcode: "3307216167259",
      serial: "CUSA-18534",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. No se añade Nueva Zelanda automáticamente."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-us-a",
      label: "Standard Edition · USA A",
      broadRegion: "NORTH_AMERICA",
      editionType: "STANDARD",
      marketRegions: ["US"],
      ratingSystems: ["ESRB"],
      barcode: "887256110116",
      serial: "CUSA-18522",
      catalogIds: ["ps4-usa-assassin%27s-creed-valhalla"],
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. UPC principal Standard; no se sustituye por 887256110123."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-us-b",
      label: "Standard Edition · USA B / candidata retailer-reprint",
      broadRegion: "NORTH_AMERICA",
      editionType: "STANDARD",
      marketRegions: ["US"],
      barcode: "887256110123",
      evidenceIds: ["valhalla-us-standard-b"],
      notes: ["Estado: NEEDS_PHYSICAL_MAPPING. Portada, retailer, bonus insert y revisión de fabricación pendientes."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-ca",
      label: "Standard Edition · Canadá bilingüe",
      broadRegion: "NORTH_AMERICA",
      editionType: "STANDARD",
      marketRegions: ["CA"],
      packagingLanguages: ["EN", "FR"],
      barcode: "887256110130",
      evidenceIds: ["valhalla-canada-retail"],
      notes: ["Confianza: CONFIRMED_DISTINCT_CANADIAN_SKU. Evidencia retail bilingüe fuerte; confirmar el scan físico exacto."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-jp",
      label: "Standard Edition · Japón",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244010962",
      serial: "PLJM-16677",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. CERO Z; el código físico PLJM se mantiene separado de la familia digital CUSA-18524."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-standard-asia",
      label: "Standard Edition · Asia Multi-Language",
      broadRegion: "ASIA",
      editionType: "STANDARD",
      evidenceIds: ["valhalla-asia-language"],
      notes: ["Confianza: CONFIRMED_EXISTENCE. Familia digital CUSA-18524; barcode, product code físico y packaging pendientes.", "Software documentado: EN/JA/ZH-Hans/ZH-Hant/KO. No se mezcla con Japón ni con una Corea física aún no confirmada."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-gold-eu",
      label: "Gold Edition · Europa genérica",
      broadRegion: "EUROPE",
      editionType: "DELUXE",
      barcode: "3307216168553",
      serial: "CUSA-18534",
      physicalContents: ["Juego base"],
      digitalContents: ["Season Pass"],
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Regionalizaciones internas y packaging pendientes."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-gold-steelbook-us",
      label: "Gold Steelbook Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "STEELBOOK",
      marketRegions: ["US"],
      barcode: "887256110628",
      serial: "CUSA-18522",
      physicalContents: ["Juego base", "Steelbook"],
      digitalContents: ["Season Pass"],
      catalogIds: ["ps4-usa-assassin%27s-creed-valhalla-gold-edition"],
      evidenceIds: ["valhalla-gamestop-gold"],
      notes: ["Confianza: CONFIRMED. La ficha y su precio existentes se preservan."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-gold-au",
      label: "Gold Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "DELUXE",
      marketRegions: ["AU"],
      barcode: "3307216167198",
      serial: "CUSA-18534",
      physicalContents: ["Juego base"],
      digitalContents: ["Season Pass"],
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-gold-steelbook-au",
      label: "Gold Steelbook Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "STEELBOOK",
      marketRegions: ["AU"],
      barcode: "3307216169413",
      serial: "CUSA-18534",
      physicalContents: ["Juego base", "Steelbook"],
      digitalContents: ["Season Pass"],
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. No se fusiona con Gold Australia 3307216167198."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-ultimate-eu-game",
      label: "Ultimate Edition · Europa / GAME Exclusive",
      broadRegion: "EUROPE",
      editionType: "DELUXE",
      barcode: "3307216168423",
      serial: "CUSA-18534",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. Se mantiene separada de Standard y Gold."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-ultimate-steelbook-us",
      label: "Ultimate Steelbook Edition · USA",
      broadRegion: "NORTH_AMERICA",
      editionType: "STEELBOOK",
      marketRegions: ["US"],
      barcode: "887256110642",
      serial: "CUSA-18522",
      physicalContents: ["Juego base", "Steelbook"],
      digitalContents: ["Season Pass", "Ultimate Pack"],
      catalogIds: ["ps4-usa-assassin%27s-creed-valhalla-ultimate-edition"],
      evidenceIds: ["valhalla-gamestop-ultimate"],
      notes: ["Confianza: CONFIRMED. GameStop Exclusive; ficha y precio existentes preservados."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-ultimate-au",
      label: "Ultimate Edition · Australia",
      broadRegion: "OCEANIA",
      editionType: "DELUXE",
      marketRegions: ["AU"],
      barcode: "3307216167228",
      serial: "CUSA-18534",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-ultimate-jp",
      label: "Ultimate Edition · Japón",
      broadRegion: "ASIA",
      editionType: "DELUXE",
      marketRegions: ["JP"],
      packagingLanguages: ["JA"],
      ratingSystems: ["CERO"],
      barcode: "4949244010979",
      serial: "PLJM-16678",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. CERO Z; no se mezcla con Standard PLJM-16677."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-limited-fr-eu",
      label: "Limited Edition · Francia / Europa",
      broadRegion: "EUROPE",
      editionType: "LIMITED",
      marketRegions: ["FR"],
      packagingLanguages: ["FR"],
      barcode: "3307216168782",
      evidenceIds: ["valhalla-limited-fr"],
      notes: ["Confianza: CONFIRMED. No representa automáticamente toda Europa."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-drakkar-eu",
      label: "Drakkar Edition · Europa",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      barcode: "3307216168904",
      serial: "CUSA-18535",
      evidenceIds: ["valhalla-gamefaqs-release-data"],
      notes: ["Confianza: CONFIRMED. País y packaging pendientes; no se colapsa con CUSA-18534."],
    }),
    ...[
      ["eu", "Europa genérica", "3307216232650", "EUROPE", [], undefined, undefined],
      ["fr", "Francia", "3307216232759", "EUROPE", ["FR"], undefined, undefined],
      ["au", "Australia", "3307216232728", "OCEANIA", ["AU"], undefined, undefined],
      ["jp", "Japón", "4949244012720", "ASIA", ["JP"], "PLJM-16994", "2022-03-10"],
    ].map(([suffix, label, barcode, broadRegion, marketRegions, serial, releaseDate]) => physicalEdition({
      id: `ac-valhalla-ps4-ragnarok-${suffix}`,
      label: `Ragnarök Edition · ${label}`,
      broadRegion,
      editionType: "SPECIAL",
      marketRegions,
      packagingLanguages: suffix === "jp" ? ["JA"] : [],
      ratingSystems: suffix === "jp" ? ["CERO"] : suffix === "au" ? ["ACB MA15+"] : suffix === "eu" || suffix === "fr" ? ["PEGI"] : [],
      barcode,
      serial,
      releaseDate,
      physicalContents: ["Assassin's Creed Valhalla base game disc"],
      digitalContents: ["Código de descarga de Dawn of Ragnarök"],
      evidenceIds: suffix === "fr" ? ["valhalla-ragnarok-fr"] : suffix === "au" ? ["valhalla-ragnarok-au"] : suffix === "jp" ? ["valhalla-ragnarok-jp"] : ["valhalla-gamefaqs-release-data"],
      notes: ["Tipo semántico: BASE_GAME_PLUS_EXPANSION_CODE. Es una edición del juego base, no la expansión autónoma ni un Code in a Box sin disco."],
    })),
    physicalEdition({
      id: "ac-valhalla-ps4-ragnarok-pal-catalog-pending",
      label: "Ragnarök Edition · ficha PAL España existente / SKU pendiente",
      broadRegion: "EUROPE",
      editionType: "SPECIAL",
      physicalContents: ["Assassin's Creed Valhalla base game disc"],
      digitalContents: ["Código de descarga de Dawn of Ragnarök"],
      catalogIds: ["ps4-assassin%27s-creed-valhalla-ragnarok-edition"],
      notes: ["Tipo semántico: BASE_GAME_PLUS_EXPANSION_CODE. Se conservan URL, portada y precio provisionales; el dossier no cierra su EAN/mercado físico exacto."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-ragnarok-us-platform-pending",
      label: "Ragnarök Edition · USA / plataforma de UPC pendiente",
      broadRegion: "NORTH_AMERICA",
      editionType: "SPECIAL",
      physicalContents: ["Assassin's Creed Valhalla base game disc"],
      digitalContents: ["Código de descarga de Dawn of Ragnarök"],
      catalogIds: ["ps4-usa-assassin%27s-creed-valhalla-ragnarok-edition"],
      evidenceIds: ["valhalla-ragnarok-us-conflict"],
      notes: ["Tipo semántico: BASE_GAME_PLUS_EXPANSION_CODE. UPC candidato 887256112639 queda en PLATFORM_MAPPING_NEEDS_VERIFICATION y no se publica como barcode PS4 confirmado."],
    }),
    physicalEdition({
      id: "ac-valhalla-ps4-collector-us-existing",
      label: "Collector's Edition · USA / ficha existente",
      broadRegion: "NORTH_AMERICA",
      editionType: "COLLECTOR",
      marketRegions: ["US"],
      catalogIds: ["ps4-usa-assassin%27s-creed-valhalla-collector%27s-editions"],
      notes: ["Ficha pública, URL, portada y precio existentes preservados. El dossier entregado no aporta identificadores físicos suficientes para ampliarla."],
    }),
  ],
  evidence: [
    evidence("valhalla-owned-scan-es", "REAL_SCAN", "Escaneos propios de la Standard PAL España", undefined, "Portada, contraportada y lomo del ejemplar precintado confirman caja española, EAN 3307216168379 y CUSA-18534.", ["Standard España", "EAN", "CUSA", "packaging español"]),
    evidence("valhalla-spain-retail", "RETAILER_PHOTO_CONFIRMED", "RetroLoco/Fnac/PcComponentes · Standard España", "https://www.retroloco.es/producto/assassins-creed-valhalla-esp/", "Confirma PAL España, EAN 3307216168379, CUSA-18534 y carátula/manual español.", ["Standard España"]),
    evidence("valhalla-france-retail", "RETAILER_PHOTO_CONFIRMED", "RetroLoco/Fnac Francia · caja FR/NL", "https://www.retroloco.es/producto/assassins-creed-valhalla-fra/", "Confirma EAN 3307216168287, CUSA-18534 y packaging FR/NL.", ["Standard Francia/Benelux"]),
    evidence("valhalla-poland-retail", "RETAILER_PHOTO_CONFIRMED", "Gamefinity/listing físico · Polonia", "https://gamefinity.pl/produkt/assassins-creed-valhalla-pl-ps4", "Confirma EAN 3307216168348 y portada polaca.", ["Standard Polonia"]),
    evidence("valhalla-english-pack", "RETAILER_PHOTO_CONFIRMED", "Miravia/eBay UK · caja inglesa", "https://www.miravia.es/p/assassins-creed-valhalla-juego-para-consola-sony-playstation-4-ps4-i1356428560332807.html", "Confirma EAN 3307216168362 y contraportada inglesa.", ["Standard English packaging"]),
    evidence("valhalla-austria-retail", "RETAILER_PHOTO_CONFIRMED", "GameNatiX · PEGI-AT", "https://www.gamenatix.de/assassins-creed-valhalla-ps4-gebraucht-pegi-at.html", "Confirma EAN 3307216168324 como variante Austria/PEGI-AT.", ["Standard Austria"]),
    evidence("valhalla-italy-market", "RETAILER_ASSET", "GamesandMovies Italia · caja inglesa", "https://www.gamesandmovies.it/", "El dossier documenta EAN 3307216168294 vendido en Italia con cover inglesa y software italiano.", ["Italy-market English-cover candidate"]),
    evidence("valhalla-eu-pending", "RETAILER_ASSET", "RetroBroker/retailers UE · EAN sin cerrar", "https://www.retrobroker.com/", "Vincula 3307216168317 a CUSA-18534 sin resolver su identidad territorial.", ["EU pending mapping"]),
    evidence("valhalla-gamefaqs-release-data", "UNKNOWN", "GameFAQs · datos de lanzamiento suministrados", "https://gamefaqs.gamespot.com/ps4/289109-assassins-creed-valhalla/data", "Fuente agregada del dossier para SKU y ediciones; los conflictos de plataforma y mercados permanecen pendientes.", ["Standard", "Gold", "Ultimate", "Drakkar", "Ragnarök"]),
    evidence("valhalla-us-standard-b", "RETAILER_ASSET", "Best Buy · segundo UPC Standard", "https://www.bestbuy.com/", "Registra 887256110123 como Standard; revisión física exacta pendiente.", ["USA Standard B"]),
    evidence("valhalla-canada-retail", "RETAILER_ASSET", "Toys R Us Canada · Standard bilingüe", "https://www.toysrus.ca/en/PlayStation-4-Assassins-Creed-Valhalla/64D6FB7C.html", "Confirma UPC 887256110130 y producto bilingüe canadiense.", ["Canada Standard"]),
    evidence("valhalla-asia-language", "RETAILER_ASSET", "Play-Asia/PlayStation Asia · Multi-Language", "https://www.play-asia.com/en/assassins-creed-valhalla-multi-language/13/70dxjn", "Confirma existencia física Asia y software EN/JA/ZH-Hans/ZH-Hant/KO; identificadores físicos pendientes.", ["Asia Standard"]),
    evidence("valhalla-gamestop-gold", "RETAILER_ASSET", "GameStop · Gold Steelbook USA", "https://www.gamestop.com/video-games/playstation-4/products/assassins-creed-valhalla-gold-steelbook-edition---playstation-4/215855.html", "Confirma base game, Steelbook, Season Pass y UPC 887256110628.", ["Gold Steelbook USA"]),
    evidence("valhalla-gamestop-ultimate", "RETAILER_ASSET", "GameStop · Ultimate Steelbook USA", "https://www.gamestop.com/video-games/playstation-4/products/assassins-creed-valhalla-ultimate-steelbook-edition---playstation-4-gamestop-exclusive/215859.html", "Confirma base game, Steelbook, Season Pass, Ultimate Pack y UPC 887256110642.", ["Ultimate Steelbook USA"]),
    evidence("valhalla-limited-fr", "RETAILER_PHOTO_CONFIRMED", "Trader Games · Limited francesa/europea", "https://www.tradergames.fr/", "Confirma EAN 3307216168782 y texto físico francés.", ["Limited Edition Francia/Europa"]),
    evidence("valhalla-ragnarok-fr", "RETAILER_ASSET", "Fnac France · Ragnarök Edition", "https://www.fnac.com/a16632201/Assassin-s-Creed-Valhalla-Edition-Ragnarok-PS4-Jeu-video-PlayStation-4", "Confirma juego base en disco más código de L'Aube du Ragnarök, EAN 3307216232759.", ["Ragnarök Edition Francia", "base disc", "expansion code"]),
    evidence("valhalla-ragnarok-au", "RETAILER_ASSET", "Gamesmen Australia · Ragnarök Edition", "https://www.gamesmen.com.au/ps4-assassins-creed-valhalla-ragnarok-edition", "Confirma EAN 3307216232728, PAL, MA15+ y lanzamiento australiano.", ["Ragnarök Edition Australia"]),
    evidence("valhalla-ragnarok-jp", "RETAILER_ASSET", "Rakuten/Nojima/MediaWorld Japón · Ragnarök Edition", "https://books.rakuten.co.jp/rb/17031859/", "Confirma disco base, código Dawn of Ragnarök, JAN 4949244012720 y PLJM-16994.", ["Ragnarök Edition Japón", "base disc", "expansion code"]),
    evidence("valhalla-ragnarok-us-conflict", "UNKNOWN", "Conflicto de plataforma del UPC Best Buy", "https://gamefaqs.gamespot.com/ps4/289109-assassins-creed-valhalla/data", "GameFAQs sitúa 887256112639 en PS4, pero la ficha Best Buy indexada corresponde a Xbox; no se confirma como UPC PS4.", ["Ragnarök USA pending"]),
  ],
  sources: [
    { label: "Orden local: regionatlas_codex_ac_valhalla_worldwide_variants.md" },
    { label: "Escaneos propios registrados en RegionAtlas" },
  ],
  evidenceNote: "No se realizó investigación externa. Retailer country no equivale a mercado físico; idiomas de software no equivalen a idiomas de caja. Los huecos de Portugal, Alemania, Nordic, Italia IT-only, Nueva Zelanda, México/LATAM, Brasil, Corea y Asia permanecen pendientes.",
};

const dawnOfRagnarokGuide = {
  schemaVersion: 2,
  id: "assassins-creed-valhalla-dawn-of-ragnarok-ps4",
  title: "Producto físico de código de Assassin's Creed Valhalla: Dawn of Ragnarök en PlayStation 4",
  reviewedAt: REVIEWED_AT,
  note: "Dawn of Ragnarök es una expansión de Assassin's Creed Valhalla. Sus cajas Code in a Box son productos físicos de descarga sin disco y no son ediciones físicas del juego base.",
  game: {
    title: "Assassin's Creed Valhalla: Dawn of Ragnarök",
    platformSlug: "ps4",
    canonicalCatalogId: "ps4-assassins-creed-valhalla-dawn-of-ragnarok",
  },
  physicalEditions: [
    physicalEdition({
      id: "ac-valhalla-dawn-ragnarok-ps4-code-box-eu",
      label: "Dawn of Ragnarök · Code in a Box · Europa / ficha existente",
      broadRegion: "EUROPE",
      editionType: "OTHER",
      physicalContents: ["Caja física", "Sin disco"],
      digitalContents: ["Código de descarga de la expansión Dawn of Ragnarök"],
      catalogIds: ["ps4-assassins-creed-valhalla-dawn-of-ragnarok"],
      evidenceIds: ["valhalla-dawn-code-box"],
      notes: ["Tipo: PHYSICAL_DOWNLOAD_CODE. Requiere Assassin's Creed Valhalla; identifiers PS4-specific y mercado exacto pendientes.", "EAN candidatos 3307216234470 y 3307216234364 permanecen en backlog sin asignarse a PS4 por posibles mezclas con Xbox."],
    }),
    physicalEdition({
      id: "ac-valhalla-dawn-ragnarok-ps4-code-box-us",
      label: "Dawn of Ragnarök · Code in a Box · USA / ficha existente",
      broadRegion: "NORTH_AMERICA",
      editionType: "OTHER",
      physicalContents: ["Caja física", "Sin disco"],
      digitalContents: ["Código de descarga de la expansión Dawn of Ragnarök"],
      catalogIds: ["ps4-usa-assassins-creed-valhalla-dawn-of-ragnarok"],
      evidenceIds: ["valhalla-dawn-code-box"],
      notes: ["Tipo: PHYSICAL_DOWNLOAD_CODE. Requiere el juego base; UPC/product code y correspondencia física exacta pendientes."],
    }),
  ],
  evidence: [
    evidence("valhalla-dawn-code-box", "UNKNOWN", "Dossier entregado · Dawn of Ragnarök Code in a Box", "https://gamefaqs.gamespot.com/ps4/289109-assassins-creed-valhalla/data", "Documenta productos físicos que contienen únicamente un código; las tablas agregadas mezclan plataformas para algunos EAN.", ["expansión", "sin disco", "requiere juego base", "EAN pending"]),
  ],
  sources: [
    { label: "Orden local: regionatlas_codex_ac_valhalla_worldwide_variants.md" },
  ],
  evidenceNote: "Relación semántica: Dawn of Ragnarök = EXPANSION, expansionOf ps4-assassins-creed-valhalla. Code in a Box = PHYSICAL_DOWNLOAD_CODE, containsDisc false. No se asignan EAN dudosos a PS4.",
};

function addSingleNavigationFamily(guide) {
  guide.editionFamilies = [{
    id: "documented-worldwide-editions",
    label: "Ediciones físicas documentadas",
    representativeCatalogId: guide.game.canonicalCatalogId,
    physicalEditionIds: guide.physicalEditions.map((edition) => edition.id),
    priceConditions: ["sealed", "newRetail", "complete"],
  }];
}

for (const guide of [unityGuide, valhallaGuide, dawnOfRagnarokGuide]) addSingleNavigationFamily(guide);

const document = { schemaVersion: 2, guides: [unityGuide, valhallaGuide, dawnOfRagnarokGuide] };
const serialized = `${JSON.stringify(document, null, 2)}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    // The comparison below reports the missing generated artifact.
  }
  if (current !== serialized) {
    console.error("catalog-edition-guides-ac-unity-valhalla.json is not up to date");
    process.exitCode = 1;
  } else {
    console.log("Assassin's Creed Unity and Valhalla V2 guides are reproducible");
  }
} else {
  writeFileSync(OUTPUT_PATH, serialized);
  console.log(`Wrote ${OUTPUT_PATH}`);
}
